import React from "react";
import Register_Page from "./Register_Page";
export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};
function Register() {


  
  return (
    <div>
      <Register_Page/>
    </div>
  );
}

export default Register;
