import Footer from "./footer";
import Meta from "./Meta";
import Navbar from "./navbar";
export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

function Home() {
  return (
    <div>
      <Navbar />
      <Meta />
      <Footer/>
    </div>
  );
}

export default Home;
