import React from 'react'
import Contact from './contact'
export const metadata = {
    title: "Contacts",
    description: "Generated by create next app",
  };
function page() {
  return (
    <div>
      <Contact/>
    </div>
  )
}

export default page
